platform :ios, '11.0'
use_frameworks!
inhibit_all_warnings!
# pod的本地索引文件：~/Library/Caches/CocoaPods/search_index.json

source 'https://github.com/CocoaPods/Specs.git'
source 'https://gitee.com/dvlproad/dvlproadSpecs' 

post_install do |installer|
    
    puts 'Determining pod project minimal deployment target'
    
    pods_project = installer.pods_project
    deployment_target_key = 'IPHONEOS_DEPLOYMENT_TARGET'
    deployment_targets = pods_project.build_configurations.map{ |config| config.build_settings[deployment_target_key] }
    minimal_deployment_target = deployment_targets.min_by{ |version| Gem::Version.new(version) }
    
    puts 'Minimal deployment target is ' + minimal_deployment_target
    puts 'Setting each pod deployment target to ' + minimal_deployment_target
    
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings[deployment_target_key] = minimal_deployment_target
        end
    end
end

source 'https://github.com/CocoaPods/Specs.git'

inhibit_all_warnings! #inhibit_warnings参数能够有效的抑制CocoaPods引入的第三方代码库产生的warning。

target 'CJUIKitDemo' do
    pod 'CQDemoKit',   :subspecs => ['BaseVC']
  
    pod 'Masonry'

    pod 'IQKeyboardManager'
    pod 'UINavigation-SXFixSpace'
    
    pod 'TSDemo_DataVientiane',       :path => '../'
    pod 'TSDemo_DataVientiane-Swift', :path => '../'
    pod 'CJDataVientianeSDK',         :path => '../'
    pod 'CJDataVientianeSDK-Swift',   :path => '../'
end

#target 'CJUIKitDemoTests' do
#    platform :ios, '9.0'
#    #pod 'OCMock', '~> 3.4.1'
#    pod 'CJBaseTest/Test',      :path => '../'
#end
#
#target 'CJUIKitDemoUITests' do
#    platform :ios, '9.0'
#    pod 'CJBaseTest/UITest',    :path => '../'
#end
